### ISSUE TITLE
Mangling with somajs

### ISSUE THREAD

**Issue by soundstep** [gregbown/soma-redux-i18next-webpack#1]
Hi Greg, interesting work.

The "minification" alongside the dependency injection can be managed so it doesn't break, you have 2 options:

- Best for file size, not best for syntax: specifying an `inject` static array as described [here](https://github.com/soundstep/infuse#specified-inject-value-minification)

Short example:

```
var Person = function(injectedName) {
	this.name = injectedName;
}
// specify injected arguments so that it works with minified code
Person.inject = ["injectedName"];
```

- Best for syntax, not best for file size: completely disable the "mangling", more info [there](https://groups.google.com/u/1/g/somajs/c/twPrU9_wLhQ/m/dQyNjPhJ71AJ)

With webpack, there seem to be a mangling option to investigate:
https://webpack.js.org/plugins/terser-webpack-plugin/

More info there too:
https://stackoverflow.com/questions/54660674/more-extensive-mangling-terser-webpack-plugin

**Comment by gregbown** [comment]
@soundstep Hi Romuald,  thank you for your response, and of course your advice.  I did experiment previously with all the terser plugin settings for a few hours but the documentation is terrible and seems to be some cryptic combination between the language in terser and what keys are mapped to in the Webpack plugin.  After a few more hours, I managed to stumble onto the exact combination (see below) which gets me down to 111kb for the all the JavaScript, finally!!!  Thank you again Romuald

```
          mangle: {
            properties: false,
            reserved: [
              "emitter",
              "rws",
              "loader",
              "renderer",
              "actions",
              "todos",
              "filter",
              "locale",
              "reducers",
              "configuration",
              "store",
              "head",
              "input",
              "list",
              "foot"
            ]
          },
```
